# coding=UTF-8
# -----------------------------------------------
# Generated by InVEST 3.11.0.post370+g6f7ec767a.d20220826 on Fri Aug 26 15:05:17 2022
# Model: Sediment Delivery Ratio

import logging
import sys

import natcap.invest.sdr.sdr
import natcap.invest.utils

LOGGER = logging.getLogger(__name__)
root_logger = logging.getLogger()

handler = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter(
    fmt=natcap.invest.utils.LOG_FMT,
    datefmt='%m/%d/%Y %H:%M:%S ')
handler.setFormatter(formatter)
logging.basicConfig(level=logging.INFO, handlers=[handler])

args = {
    'biophysical_table_path': 'SDR/biophysical_table_Gura.csv',
    'dem_path': 'wangandliu.sdat',
    'drainage_path': '',
    'erodibility_path': 'SDR/erodibility_gura.tif',
    'erosivity_path': 'SDR/erosivity_gura.tif',
    'ic_0_param': '0.5',
    'k_param': '2',
    'l_max': '122',
    'lulc_path': 'SDR/land_use_gura.tif',
    'sdr_max': '0.8',
    'threshold_flow_accumulation': '1000',
    'watersheds_path': 'SDR/watershed_gura.shp',
    'workspace_dir': 'sdr-with-modified-ls-factor-workspace',
}

if __name__ == '__main__':
    natcap.invest.sdr.sdr.execute(args)
